<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tgm_formhandler_tmplbuilder"
 *
 * Auto generated by Extension Builder 2016-09-26
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'TgM Formhandler Templatebuilder',
	'description' => 'Fluid based template building of formhandler mastertemplate with many predefined partials. It is possible to configure the fe an submitted partial in one and the same fluid-template.
Works with bootstrap, jquery and jquery formvalidation.',
	'category' => 'templates',
	'author' => 'Paul Beck, Steffen Thierock',
	'author_email' => 'pb@teamgeist-medien.de, st',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
			'formhandler' => '',
			'vhs' => ''
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);